# Generated by Django 3.2 on 2021-05-16 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Anime', '0011_alter_anime_synopsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TW', 'To watch'), ('WG', 'Watching'), ('WD', 'Watched')], default='TW', max_length=2)),
                ('last_episode_watched', models.IntegerField(blank=True, default=0)),
                ('anime', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Anime.anime')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='No description')),
                ('animes', models.ManyToManyField(blank=True, to='Lists.AnimeCardList')),
            ],
        ),
    ]
