# Generated by Django 3.2 on 2021-05-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0002_auto_20210516_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.CharField(default='', max_length=5),
        ),
    ]
