# Generated by Django 3.1.7 on 2021-04-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(choices=[('Manga', 'Manga'), ('Anime', 'Anime')], max_length=5),
        ),
    ]
