# Generated by Django 3.2 on 2021-05-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0004_alter_genre_mal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
