# Generated by Django 3.2 on 2021-05-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0003_auto_20210501_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='mal_id',
            field=models.IntegerField(unique=True),
        ),
    ]
