# Generated by Django 3.1.7 on 2021-04-04 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Studio', '0001_initial'),
        ('Genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
                ('trailer_url', models.URLField()),
                ('titles', models.TextField()),
                ('score', models.DecimalField(decimal_places=3, max_digits=3)),
                ('scored_by', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('episodes', models.IntegerField()),
                ('broadcast', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Genres.type')),
            ],
        ),
        migrations.CreateModel(
            name='Studios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_mal_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Anime.anime')),
                ('studio_mal_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Studio.studio')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Genres.type')),
            ],
        ),
    ]
