# Generated by Django 3.1.7 on 2021-05-01 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0005_auto_20210501_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='anime',
            name='publication_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=0),
        ),
    ]
