# Generated by Django 3.2 on 2021-05-02 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0005_alter_genre_id'),
        ('Studio', '0002_auto_20210501_1813'),
        ('Anime', '0007_auto_20210501_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, to='Genres.Genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='last_update',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(blank=True, to='Studio.Studio'),
        ),
    ]
