# Generated by Django 3.2 on 2021-05-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0008_auto_20210501_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.CharField(blank=True, default=0.0, max_length=5),
        ),
    ]
