# Generated by Django 3.2 on 2021-05-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0009_alter_anime_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/embed/0vRJPLNF5Cs'),
        ),
    ]
