# Generated by Django 3.2 on 2021-05-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0010_alter_anime_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='synopsis',
            field=models.TextField(blank=True, default='No synopsis'),
        ),
    ]
