# Generated by Django 3.1.7 on 2021-04-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='img_url',
            new_name='image_url',
        ),
    ]
