# Generated by Django 3.1.7 on 2021-05-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0003_auto_20210501_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='broadcast',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rank',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='anime',
            name='scored_by',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='synopsis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='titles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True),
        ),
    ]
