# Generated by Django 3.1.7 on 2021-05-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0004_auto_20210501_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='titles',
            field=models.TextField(blank=True, help_text="{'title': 'Hunter x Hunter (2011)', 'title_english': 'Hunter x Hunter', 'title_japanese': 'HUNTER×HUNTER（ハンター×ハンター）','title_synonyms': ['HxH (2011)']}"),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('MG', 'Manga'), ('AN', 'Anime')], default='AN', max_length=2),
        ),
    ]
