# Generated by Django 3.1.7 on 2021-05-01 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Anime', '0004_auto_20210501_1817'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('privacy', models.BooleanField(default=True, help_text='True = Public, False = Private ')),
                ('description', models.TextField(default='')),
                ('animes', models.ManyToManyField(to='Anime.Anime')),
                ('user_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
